---
- name: Check if {{ kubectl_home }}/.kube/config file exists
  stat:
    path: '{{ kubectl_home }}/.kube/config'
  register: kube_config

- name: Run kubeadm init
  command: >
    kubeadm init   --pod-network-cidr {{ ip_flannel }}   --apiserver-advertise-address {{ hostvars[item].ansible_host }}
  with_items: "{{ groups.master }}"
  when: kube_config.stat.exists

- name: Create {{ kubectl_home }}/.kube dir
  file:
    path: '{{ kubectl_home }}/.kube'
    state: directory
    mode: 0755

- name: Copy file {{ kubectl_home }}/.kube/config and change owners
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: '{{ kubectl_home }}/.kube/config'
    owner: "{{ kubectl_user }}"
    group: "{{ kubectl_group }}"
    mode: 0500

- name: Get join command
  command: >
    kubeadm token create --print-join-command
  register: kubeadm_join
  changed_when: kubeadm_join.rc == 0

- name: Copy join command
  copy:
    content: '{{ kubeadm_join.stdout }}'
    dest: './join-command'
  delegate_to: localhost
