---
- name: Create /etc/yum.repos.d/ dir
  file:
    path: /etc/yum.repos.d/
    state: directory
    mode: 0644
    owner: "{{ host_user }}"
    group: "{{ host_group }}"

- name: Modify /etc/yum.repos.d/kubernetes.repo file
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    force: no

- name: Install Kubernetes
  yum:
    name: ['kubeadm-{{ kube_version }}','kubectl-{{ kube_version }}','kubelet-{{ kube_version }}']
    state: present
  notify: Kubelet service
