---
- name: Install ntp
  yum:
    name: ntp
    state: present

- name: Open ports firewalld
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
  notify:
  - Restart firewalld

- name: Config ntp
  template:
    src:  ntp.conf.j2
    dest: /etc/ntp.conf
    force: yes
  notify:
  - ntpd service

