---
- name: Disable Selinux 
  selinux:
    state: disabled

- name: Reboot
  reboot:

- name: Disable swap 1
  replace:
    path: /etc/fstab
    regexp: '/dev/mapper/centos-swap'
    replace: '#/dev/mapper/centos-swap'

- name: Disable swap 2
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Create /etc/sysctl.d/k8s.conf file
  file:
    path: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644
    state: touch

- name: Modify /etc/sysctl.d/k8s.conf file
  template:
    src: iptables.cnf.j2
    dest: /etc/sysctl.d/k8s.conf

- name: Add masquerade firewalld
  firewalld:
    masquerade: yes
    permanent: yes
    state: enabled

- name: Open ports firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 8472/udp
    - 10250/tcp
  notify:
  - Restart firewalld

